### ISSUE TITLE
Crash after  transition to "Series" with existence of publishers in database.

### ISSUE THREAD

**Issue by ARK215** [okolobaxa/postcards#3]
After adding of one or more publishers in "Publishers", site crashes on click on "Series"
Error in Views\Series\Index.cshtml    Line: 30 as seen on screenshot.

Expected: Successful transition to "Series"

![image](https://cloud.githubusercontent.com/assets/13455967/8891171/53db0ff8-3327-11e5-823c-0805f1de5e27.png)

**Comment by okolobaxa** [comment]
fixed in https://github.com/oldsaratov/postcards/commit/5b5c014c3c95fa0afb41e15d95bbc401c2d63e1d

**Comment by ARK215** [comment]
Still not fixed 
![image](https://cloud.githubusercontent.com/assets/13455967/8894867/21cc0254-33ce-11e5-8bcf-d5655a98ec1e.png)
